hydra:
  run:
    dir: ${exp_dir}/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${exp_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job_logging:
    root:
      level: INFO

defaults:
  - prompt: base_completion
  - language_model: gpt-3.5-turbo
  - dataset: random_words

# Common Params
study_dir: exp/default_dir
exp_dir: ${study_dir}/base_${language_model.model}_${prompt.method}_prompt_${dataset.topic}_dataset
seed: 0
limit: 50
reset: false
logging: INFO
print_prompt_and_response: false
cache_dir: ${exp_dir}/cache
prompt_history_dir: ${exp_dir}/prompt_history

# Model
language_model:
  temperature: 0.0
  logprobs: 2

# API
organization: OWAIN_ORG
anthropic_tag: ANTHROPIC_API_KEY
openai_tag: OPENAI_API_KEY
anthropic_num_threads: 2
openai_fraction_rate_limit: 0.9
