hydra:
  run:
    dir: ${exp_dir}/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${exp_dir}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job_logging:
    root:
      level: INFO

defaults:
  - prompt: object_level/minimal
  - language_model: gpt-3.5-turbo
  - task: wikipedia

# Common Params
study_name: ???
study_dir: exp/${study_name}
exp_dir: ${sanitize:${study_dir}/object_level_${language_model.model}_${prompt.method}_prompt_${task.name}_task}_${note}_note
note: "" # natural language description of the note of this run. Can be anything.
seed: 0
limit: 500
strings_path: none # if set, use the strings from this file rather than generating them from the dataset
filter_strings_path: none # if this is set, use this to filter the strings

reset: false
logging: INFO
print_prompt_and_response: false
cache_dir: ${exp_dir}/cache
prompt_history_dir: ${exp_dir}/prompt_history

# Model
language_model:
  temperature: 0.0
  logprobs: 2

task:
  num: ${limit}

# API
organization: OWAIN_ORG
anthropic_tag: ANTHROPIC_API_KEY
openai_tag: OPENAI_API_KEY
anthropic_num_threads: 2
openai_fraction_rate_limit: 0.9
